### PR TITLE
add a simple example to help user to get started

### PR DESCRIPTION
**Pull request by weijianzhg**
ref #111

### CODE REVIEW

**Comment by weijianzhang** [comment]
Any comments? @mlubin @sbromberger @yeesian

**Comment by yeesian** [comment]
apart from jiahao's comment, LGTM

**Comment by mlubin** [comment]
LGTM

**Comment by sbromberger** [comment]
+1 - looks great.

**Comment by weijianzhang** [comment]
Thanks, just changed to the double colon syntax for code block.

**Comment by mlubin** [comment]
@weijianzhang, did you build the documentation locally to check that it's formatted correctly?

**Comment by weijianzhang** [comment]
@mlubin Yes, I did.

**Comment by mlubin** [comment]
Thanks!

**Comment by mlubin** [comment]
@lindahua, could you please share admin access to the Graphs.jl RTD page?

**Pull request merged**
