### PR TITLE
A Simple Min-Cut Algorithm

### PR DESCRIPTION
**Pull request by bdeonovic**
This is me responding to my feature request: https://github.com/JuliaLang/Graphs.jl/issues/168. An implementation that mirrors Boosts implementation of a simple min-cut algorithm

Stoer, Mechthild and Frank Wagner, “A simple min-cut algorithm”. Journal of the ACM 44 (4), 585-591, 1997. DOI: 10.1145/263867.263872

### CODE REVIEW

**Comment by mlubin** [comment]
Nice!
Could you add a few tests?

**Comment by bdeonovic** [comment]
Sure, I'll do that tomorrow.

**Comment by bdeonovic** [comment]
In my code I use 
```julia
pq = Collections.PriorirtyQueue{V,W}(Base.Order.Reverse)
```
which works in julia 0.3 but in julia 0.4 one needs
```julia
pq = Collections.PriorirtyQueue(V,W,Base.Order.Reverse)
```

Do I have to support both? If so, how?

**Comment by mlubin** [comment]
It looks like this is just used in one place. Until this is addressed in Compat, I'd just put an ``if VERSION > v"0.4.0-"`` to get the code working on 0.3 and 0.4 right now.

**Comment by bdeonovic** [comment]
How does coveralls work? Which features/functions does it track for testing?

**Comment by mlubin** [comment]
It checks which lines of code are run during the unit tests.

**Comment by Keno** [comment]
Can we switch Coveralls to the commit status notification? I hate those comments.

**Comment by mlubin** [comment]
I've requested it before, not sure who has access.

**Comment by Keno** [comment]
Maybe @StefanKarpinski?

**Comment by StefanKarpinski** [comment]
Is that on the Coveralls side or the GitHub side? @Keno, you have admin rights under JuliaLang, so that should hopefully cover the GitHub side. I'm not sure I ever did anything on the Coveralls side.

**Comment by Keno** [comment]
I can see the settings now now.  Switched it off.

**Comment by bdeonovic** [comment]
So, just out of curiosity, will this be pulled?

**Comment by mlubin** [comment]
Could you squash the commits? Otherwise looks good to merge.

**Comment by mlubin** [comment]
Oops, too late :)

**Comment by bdeonovic** [comment]
Relatively new Git user: for future reference, how do you squash commits together?

**Comment by mlubin** [comment]
``git rebase i HEAD~N`` where ``N`` is the number of commits to merge. Then you can interactively combine or rewrite the commit messages.

**Comment by pozorvlak** [comment]
Ah, sorry! Does it matter enough to back the merge out?

**Comment by mlubin** [comment]
No, I don't think so. That would just create a large mess in order to tidy up a small mess.

**Pull request merged**
