### PR TITLE
Fix 0.4 Range deprecations

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by AlainLich** [comment]
Thanks,
just tried (manually), Graphs now loads.

**Comment by milktrader** [comment]
This is one of those nice deprecations that supplies the new `UnitRange` in `v0.3` so simply changing it doesn't break things.

**Comment by scidom** [comment]
Shall we merge this to make Graphs work again with v0.4?

**Comment by scidom** [comment]
Thanks @Keno, shall we also push the changes to metadata, even without changing version (the sha1 for Graphs in metadata is more than a month old anyhow)?

**Pull request merged**
